
image: docker:latest

variables:
  REPOSITORY_URL: raihan1607/todolist_v1_app
  IMAGE_TAG: latest

services:
  - docker:dind

before_script:
  - echo $DH_PASSWORD | docker login -u $DH_USERNAME --password-stdin

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build -t todolist_v1_app:latest --build-arg PORT=$PORT --no-cache .
    - echo "Tagging image..."
    - docker tag todolist_v1_app:latest $REPOSITORY_URL:latest
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker stop todolist_v1_app || true
    - docker rm todolist_v1_app || true
    - docker container run -dt -p $PORT:$PORT --name todolist_v1_app $REPOSITORY_URL:latest
    - docker image prune -f
  only:
    - master